import time 
from selenium import webdriver
driver = webdriver.Chrome('/home/thamarai/Downloads/chromedriver')
driver.get('http://pilot.projecthubapp.com')
driver.maximize_window()
time.sleep(1)
driver.find_element_by_id('username').clear()
driver.find_element_by_id('username').send_keys('mannese@gmail.com')
time.sleep(1)
driver.find_element_by_id('password').clear()
driver.find_element_by_id('password').send_keys('arizona123')
driver.find_element_by_id('recaptcha-submit').click()
driver.find_element_by_id('project request').click()
time.sleep(1)
driver.find_element_by_class_name('btn').click()
time.sleep(1)
driver.find_element_by_class_name('radio').click()
time.sleep(1)
driver.find_element_by_id('existing_client_radio').click()
driver.find_element_by_id('order_name').send_keys('Testing')
time.sleep(1)
driver.find_element_by_id('add_new_product').click()
time.sleep(1)
driver.find_element_by_id('icon-sales').click()
time.sleep(1)
driver.find_element_by_id('goals_save').click()
driver.execute_script("window.scrollTo(0, 500)")
time.sleep(1)
driver.find_element_by_id('product_email').click()
time.sleep(1)
driver.find_element_by_id('products_save').click()
time.sleep(1)
driver.execute_script("window.scrollTo(0, 500)")
time.sleep(1)
driver.find_element_by_css_selector("button[type='button'][class='product_email btn-attention needs_attention']").click()
time.sleep(1)
driver.find_element_by_class_name('product_email').click()
driver.find_element_by_name('email_for_receipt').send_keys('mandeep@eventjini.me')
driver.find_element_by_name('email_campaign_name').send_keys('give the campaing name')
driver.find_element_by_name('from_email').send_keys('give the name here not email')
driver.find_element_by_name('email_campaign_subject').send_keys('type or paste max 50 char')
driver.find_element_by_name('destination_url').send_keys('type the destination email here')
driver.find_element_by_name('email_age_range').send_keys('Type in age range number to number')
driver.find_element_by_name('email_locations').send_keys('type,locations,by,comma,seprated')
driver.find_element_by_name('email_income').send_keys('type income range her')
driver.execute_script("window.scrollTo(0, 500)")
driver.find_element_by_name('other_demographic').send_keys('type,comma,seprated,values')
driver.find_element_by_name('userfile_email[]').send_keys('/home/thamarai/Pictures/pan.jpg')
time.sleep(1)
driver.find_element_by_id('email_save').click()
print('Report :- All the test pass for Email form \n')

driver.close()

