import time 
from selenium import webdriver
driver = webdriver.Chrome('/home/thamarai/Downloads/chromedriver')
driver.get('http://pilot.projecthubapp.com/')
driver.maximize_window()
time.sleep(1)
driver.find_element_by_id('username').clear()
driver.find_element_by_id('username').send_keys('mannese@gmail.com')
time.sleep(1)
driver.find_element_by_id('password').clear()
driver.find_element_by_id('password').send_keys('arizona123')
driver.find_element_by_id('recaptcha-submit').click()
driver.find_element_by_id('project request').click()
time.sleep(1)
driver.find_element_by_class_name('btn').click()
time.sleep(1)
driver.find_element_by_class_name('radio').click()
time.sleep(1)
driver.find_element_by_id('existing_client_radio').click()
driver.find_element_by_id('order_name').send_keys('Testing')
time.sleep(1)
driver.find_element_by_id('add_new_product').click()
time.sleep(1)
driver.find_element_by_id('icon-sales').click()
time.sleep(1)
driver.find_element_by_id('goals_save').click()
driver.execute_script("window.scrollTo(0, 300)")
time.sleep(1)
driver.find_element_by_id('products_save').click()
time.sleep(1)
driver.find_element_by_id('product_gbchooses').click()
time.sleep(1)
driver.find_element_by_css_selector("input[type='radio'][name='gb_allocate'][value='yes']").click()
time.sleep(1)
driver.execute_script("window.scrollTo(0, 400)")
time.sleep(1)
driver.find_element_by_name('monthly-budget').send_keys('20000')
driver.find_element_by_id('products_save').click()
time.sleep(1)
driver.find_element_by_xpath('/html[1]/body[1]/div[1]/div[2]/form[1]/div[3]/div[26]/div[1]/div[1]/div[3]/button[1]').click()
driver.find_element_by_name('gb_desired_margin').send_keys('type your answer here ')
driver.find_element_by_name('gb_products_notuse2').send_keys('type your instructions')
time.sleep(1)
driver.find_element_by_id('gb_start_date').click()
driver.find_element_by_class_name('next').click()
driver.find_element_by_class_name('next').click()
driver.find_element_by_xpath('/html[1]/body[1]/div[5]/div[1]/table[1]/tbody[1]/tr[6]/td[1]').click()
time.sleep(1)
driver.find_element_by_id('gb_end_date').click()
driver.find_element_by_class_name('next').click()
driver.find_element_by_class_name('next').click()
driver.find_element_by_xpath('/html[1]/body[1]/div[5]/div[1]/table[1]/tbody[1]/tr[6]/td[2]').click()
time.sleep(1)
driver.find_element_by_xpath('/html[1]/body[1]/div[1]/div[2]/form[1]/div[3]/div[27]/div[1]/div[2]/div[1]/div[3]/button[1]').click()
time.sleep(1)
driver.find_element_by_name('gbchooses_add_creative_name_of_ad-1').send_keys('anything to test')
driver.find_element_by_name('gbchooses_add_creative_name_of_cta-1').send_keys('something')
driver.find_element_by_name('gbchooses_add_creative_name_of_client_url-1').send_keys('type the url here ')
driver.find_element_by_name('gbchooses_add_creative_name_of_target_url-1').send_keys('type the target url here ')
driver.find_element_by_name('gbchooses_add_creative_name_of_ad_desc-1').send_keys('the quick brown fox jumps over the lazy dog')
time.sleep(1)
driver.find_element_by_name('userfile_gbchooses-1[]').send_keys('/home/thamarai/Pictures/0.jpeg')
time.sleep(1)
driver.find_element_by_xpath('/html[1]/body[1]/div[1]/div[2]/form[1]/div[3]/div[27]/div[1]/div[3]/div[1]/div[3]/div[1]/div[1]/div[2]/div[3]/div[1]/div[2]/button[1]').click()
time.sleep(1)
driver.find_element_by_xpath('/html[1]/body[1]/div[1]/div[2]/form[1]/div[3]/div[27]/div[1]/div[4]/button[2]/span[1]').click()
print('Report :- All the test pass for GB form \n')
driver.close()
