import time 
from selenium import webdriver
driver = webdriver.Chrome('/home/thamarai/Downloads/chromedriver')
driver.get('http://pilot.projecthubapp.com/')
driver.maximize_window()
time.sleep(1)
driver.find_element_by_id('username').clear()
driver.find_element_by_id('username').send_keys('mannese@gmail.com')
time.sleep(1)
driver.find_element_by_id('password').clear()
driver.find_element_by_id('password').send_keys('arizona123')
driver.find_element_by_id('recaptcha-submit').click()
time.sleep(1)
driver.find_element_by_id('project request').click()
time.sleep(1)
driver.find_element_by_class_name('btn').click()
time.sleep(1)
driver.find_element_by_class_name('radio').click()
time.sleep(1)
driver.find_element_by_id('existing_client_radio').click()
driver.find_element_by_id('order_name').send_keys('Testing')
time.sleep(1)
driver.find_element_by_id('add_new_product').click()
time.sleep(1)
driver.find_element_by_id('icon-sales').click()
time.sleep(1)
driver.find_element_by_id('goals_save').click()
driver.execute_script("window.scrollTo(0, 500)")
time.sleep(1)
driver.find_element_by_class_name('icon-sem').click()
time.sleep(1)
driver.find_element_by_id('products_save').click()
time.sleep(1)
driver.find_element_by_name('sem_budget').send_keys('20000')
time.sleep(1)
driver.find_element_by_name('sem_start_date').click()
driver.find_element_by_class_name('next').click()
driver.find_element_by_class_name('next').click()
driver.find_element_by_xpath('/html[1]/body[1]/div[5]/div[1]/table[1]/tbody[1]/tr[6]/td[1]').click()
time.sleep(1)
driver.find_element_by_name('sem_end_date').click()
driver.find_element_by_class_name('next').click()
driver.find_element_by_xpath('/html[1]/body[1]/div[5]/div[1]/table[1]/tbody[1]/tr[3]/td[7]').click()
driver.execute_script("window.scrollTo(0,700)")
driver.find_element_by_id('allocation_save').click()
time.sleep(1)
driver.find_element_by_xpath("//button[@class='product_sem btn-attention needs_attention']").click()
driver.find_element_by_name('sem_target_website').send_keys('type and pase the website name here ')
time.sleep(1)
driver.find_element_by_name('sem_allocation').send_keys('100000')
driver.find_element_by_name('sem_aspect').send_keys('your business should this campaign focus on')
driver.find_element_by_name('sem_specialized').send_keys('What specialized service(s)')
driver.find_element_by_name('sem_keyword_promote').send_keys('any specific keywords')
driver.find_element_by_name('sem_keyword_exclude').send_keys('Share info here')
driver.find_element_by_name('sem_competitor').send_keys('paste info here')
driver.find_element_by_name('sem_main_competitor').send_keys('name the company')
driver.find_element_by_name('sem_specific_competitor').send_keys('any specific competitors')
driver.find_element_by_name('sem_special').send_keys('share info here ')
driver.find_element_by_name('sem_region_target_location').send_keys('give, the , target , here,')
time.sleep(1)
driver.find_element_by_css_selector("input[type='radio'][name='sem_region_target'][value='USA']").click()
driver.find_element_by_name('sem_audience_target_location').send_keys('who , would, you , like, to, target')
driver.find_element_by_css_selector("input[type='radio'][name='sem_audience_target'][value='no']").click()
time.sleep(1)
driver.find_element_by_id('sem_save').click()
driver.find_element_by_class_name('icon-sem').click()
time.sleep(1)
driver.find_element_by_id('products_save').click()
print(' Report :- All the test pass for Sem form \n')
driver.close()
