from selenium import webdriver
import time
driver = webdriver.Chrome('/home/thamarai/Downloads/chromedriver')
driver.get('http://pilot.projecthubapp.com/')
driver.maximize_window()
time.sleep(1)
driver.find_element_by_id('username').clear()
driver.find_element_by_id('username').send_keys('mannese@gmail.com')
time.sleep(1)
driver.find_element_by_id('password').clear()
driver.find_element_by_id('password').send_keys('arizona123')   
driver.find_element_by_id('recaptcha-submit').click()
driver.find_element_by_id('project request').click()
time.sleep(1)
driver.find_element_by_class_name('btn').click()
time.sleep(1)
driver.find_element_by_class_name('radio').click()
time.sleep(1)
driver.find_element_by_id('existing_client_radio').click()
driver.find_element_by_id('order_name').send_keys('Testing')
driver.find_element_by_id('add_new_product').click()
driver.find_element_by_id('goal_sales').click()
time.sleep(1)
driver.find_element_by_id('goals_save').click()
driver.execute_script("window.scrollTo(0, 700)")
time.sleep(1)
driver.find_element_by_id('product_seo').click()
time.sleep(1)
driver.find_element_by_id('products_save').click()
time.sleep(1)
driver.execute_script("window.scrollTo(0, 500)")
driver.find_element_by_css_selector("button[type='button'][class='product_seo btn-attention needs_attention']").click()
driver.find_element_by_name('seo_campaign_name').send_keys('give the campaign name')
driver.find_element_by_name('seo_company_name').send_keys('give the company name')
time.sleep(1)
driver.find_element_by_name('no_of_keywords').send_keys('NUMBER OF KEYWORDS IN PROGRAM:')
time.sleep(1)
driver.find_element_by_name('userfile_seo[]').send_keys('/home/thamarai/Pictures/pan.jpg')
time.sleep(1)
driver.find_element_by_name('seo_wordpress_url').send_keys('type or paste the url here')
driver.find_element_by_name('seo_wordpress_username').send_keys('seo_wordpress_username')
driver.find_element_by_name('seo_wordpress_password').send_keys('password')
time.sleep(1)
driver.find_element_by_name('seo_cms_ftp_url').send_keys('paste your url here ')
driver.find_element_by_name('seo_cms_ftp_username').send_keys('paste your ftp user name')
driver.find_element_by_name('seo_cms_ftp_password').send_keys('type your password')
time.sleep(1)
driver.find_element_by_id('seo_save').click()
driver.find_element_by_class_name('product_seo').click()
print('Report :- All the test pass for Seo form \n')
driver.close()
