import time
from selenium import webdriver
driver = webdriver.Chrome('/home/thamarai/Downloads/chromedriver')
time.sleep(1)
driver.get('http://pilot.projecthubapp.com/')
driver.maximize_window()
time.sleep(1)
driver.find_element_by_id('username').clear()
driver.find_element_by_id('username').send_keys('mannese@gmail.com')
time.sleep(1)
driver.find_element_by_id('password').clear()
driver.find_element_by_id('password').send_keys('arizona123')   
driver.find_element_by_id('recaptcha-submit').click()
driver.find_element_by_id('project request').click()
time.sleep(1)
driver.find_element_by_class_name('btn').click()
time.sleep(1)
driver.find_element_by_class_name('radio').click()
time.sleep(1)
driver.find_element_by_id('existing_client_radio').click()
driver.find_element_by_id('order_name').send_keys('Testing')
driver.find_element_by_id('add_new_product').click()
time.sleep(1)
driver.find_element_by_id('goal_sales').click() 
time.sleep(1)
driver.find_element_by_id('goals_save').click()
driver.execute_script("window.scrollTo(0, 500)")
driver.find_element_by_id('product_social').click()
time.sleep(1)
driver.find_element_by_id('products_save').click()
time.sleep(1)
driver.execute_script("window.scrollTo(0, 500)")
driver.find_element_by_css_selector("button[type='button'][class='product_social btn-attention needs_attention']").click()
driver.find_element_by_name('social_budget').send_keys('1000000')
driver.find_element_by_name('social_paid_destination_url').send_keys('type the url here')
driver.find_element_by_name('social_paid_facebook_url').send_keys('give the url')
time.sleep(1)
driver.execute_script('document.getElementById("social_paid_start_date").removeAttribute("readonly")')
driver.find_element_by_id('social_paid_start_date').send_keys('29/03/2020')
time.sleep(1)
driver.execute_script('document.getElementById("social_paid_end_date").removeAttribute("readonly")')
driver.find_element_by_id('social_paid_end_date').send_keys('29/03/2020')
time.sleep(1)
driver.find_element_by_css_selector("input[type='radio'][name='social_paid'][value='yes']").click()
time.sleep(1)
driver.find_element_by_xpath('/html[1]/body[1]/div[1]/div[2]/form[1]/div[3]/div[15]/div[1]/div[3]/div[2]/div[2]/div[2]/div[1]/ul[1]/li[1]/input[1]').click()
driver.find_element_by_css_selector("[class='active-result highlighted'][data-option-array-index='1']").click()
time.sleep(1)
gender = driver.find_element_by_class_name('default').send_keys('Female')
driver.find_element_by_class_name('default').click()
time.sleep(1)
driver.find_element_by_xpath('/html[1]/body[1]/div[1]/div[2]/form[1]/div[3]/div[15]/div[1]/div[3]/div[3]/div[2]/div[1]/label[1]').click()
time.sleep(1)
driver.find_element_by_xpath('/html[1]/body[1]/div[1]/div[2]/form[1]/div[3]/div[15]/div[1]/div[3]/div[3]/div[2]/div[2]/label[1]').click()
time.sleep(1)
driver.find_element_by_xpath('/html[1]/body[1]/div[1]/div[2]/form[1]/div[3]/div[15]/div[1]/div[3]/div[3]/div[3]/div[1]/label[1]').click()
time.sleep(1)
driver.find_element_by_xpath('/html[1]/body[1]/div[1]/div[2]/form[1]/div[3]/div[15]/div[1]/div[3]/div[3]/div[3]/div[2]/label[1]').click()
time.sleep(1)
driver.find_element_by_xpath('/html[1]/body[1]/div[1]/div[2]/form[1]/div[3]/div[15]/div[1]/div[3]/div[3]/div[3]/div[3]/label[1]').click()
time.sleep(1)
driver.find_element_by_xpath('/html[1]/body[1]/div[1]/div[2]/form[1]/div[3]/div[15]/div[1]/div[3]/div[3]/div[4]/div[1]/label[1]').click()
time.sleep(1)
driver.find_element_by_xpath('/html[1]/body[1]/div[1]/div[2]/form[1]/div[3]/div[15]/div[1]/div[3]/div[3]/div[4]/div[2]/label[1]').click()
time.sleep(1)
driver.find_element_by_xpath('/html[1]/body[1]/div[1]/div[2]/form[1]/div[3]/div[15]/div[1]/div[3]/div[3]/div[4]/div[3]/label[1]').click()
time.sleep(1)
driver.find_element_by_name('social_target_location').send_keys('Delhi,kolkata,mumbai,chennai')
driver.find_element_by_name('social_notes').send_keys('type or paste notes here')
time.sleep(1)
driver.find_element_by_css_selector("button[type='button'][class='btn-assign social_add_content']").click()
time.sleep(1)
driver.find_element_by_name('userfile_social-paid[]').send_keys('/home/thamarai/Pictures/pan.jpg')
driver.find_element_by_name('headline_text').send_keys('Type 40 characters max')
driver.find_element_by_name('body_text').send_keys('Type max 125 characters max')
driver.find_element_by_id('social_save').click()
print('Report :- All the test pass for Social form \n')
driver.close()

