import time 
from selenium import webdriver
driver = webdriver.Chrome('/home/thamarai/Downloads/chromedriver')
driver.get('http://pilot.projecthubapp.com')
driver.maximize_window()
time.sleep(1)
driver.find_element_by_id('username').clear()
driver.find_element_by_id('username').send_keys('mannese@gmail.com')
time.sleep(1)
driver.find_element_by_id('password').clear()
driver.find_element_by_id('password').send_keys('arizona123')
driver.find_element_by_id('recaptcha-submit').click()
driver.find_element_by_id('project request').click()
time.sleep(1)
driver.find_element_by_class_name('btn').click()
time.sleep(1)
driver.find_element_by_class_name('radio').click()
time.sleep(1)
driver.find_element_by_id('existing_client_radio').click()
driver.find_element_by_id('order_name').send_keys('Testing')
time.sleep(1)
driver.find_element_by_id('add_new_product').click()
time.sleep(1)
driver.find_element_by_id('icon-sales').click()
time.sleep(1)
driver.find_element_by_id('goals_save').click()
driver.execute_script("window.scrollTo(0, 700)")
time.sleep(1)
driver.find_element_by_id('product_video').click()
time.sleep(1)

driver.find_element_by_id('prevideo_display').click()
driver.find_element_by_css_selector("input[type='radio'][name='product_service'][value='no']").click()
driver.find_element_by_id('products_save').click()
time.sleep(1)
driver.find_element_by_id('preroll_monthly_budget').send_keys('200000')
driver.find_element_by_id('preroll_cpm_sold').send_keys('1.2')
driver.find_element_by_id('preroll_btn_calculate_impressions').click()
driver.find_element_by_css_selector("input[type='radio'][name='preroll_allocate'][value='impression']").click()
time.sleep(1)
driver.find_element_by_name('preroll_no_of_impressions').send_keys('209992')
time.sleep(1)
driver.find_element_by_css_selector("input[type='radio'][name='preroll_date'][value='no']").click()
time.sleep(1)
driver.find_element_by_name('preroll_start_date').click()
driver.find_element_by_class_name('next').click()
driver.find_element_by_class_name('next').click()
driver.find_element_by_class_name('next').click()
driver.find_element_by_xpath('/html[1]/body[1]/div[5]/div[1]/table[1]/tbody[1]/tr[5]/td[3]').click()
time.sleep(1)
driver.find_element_by_id('allocation_save').click()
time.sleep(1)
driver.find_element_by_xpath('/html[1]/body[1]/div[1]/div[2]/form[1]/div[3]/div[20]/div[1]/div[1]/div[3]/button[1]').click()
time.sleep(1)
driver.find_element_by_css_selector("input[type='radio'][name='video_pre_tactics'][value='yes']").click()
time.sleep(1)
driver.find_element_by_class_name('video-pre').click()
driver.find_element_by_name('video-pre_add_creative_name_of_ad-1').send_keys('anything to test')
driver.find_element_by_name('video-pre_add_creative_name_of_cta-1').send_keys('something')
driver.find_element_by_name('video-pre_add_creative_name_of_client_url-1').send_keys('type the url here ')
driver.find_element_by_name('video-pre_add_creative_name_of_target_url-1').send_keys('type the target url here ')
driver.find_element_by_name('video-pre_add_creative_name_of_ad_desc-1').send_keys('the quick brown fox jumps over the lazy dog')
time.sleep(1)
driver.find_element_by_name("userfile_video-pre-1[]").send_keys('/home/thamarai/Pictures/0.jpeg')
time.sleep(1)
driver.find_element_by_xpath('/html[1]/body[1]/div[1]/div[2]/form[1]/div[3]/div[21]/div[1]/div[19]/div[1]/div[1]/button[2]/span[1]').click()
time.sleep(1)
driver.find_element_by_id('prevideo_display').click()
#OTT
driver.find_element_by_xpath('/html[1]/body[1]/div[1]/div[2]/form[1]/div[3]/div[6]/div[1]/div[2]/div[2]/div[2]/div[1]/span[3]').click()
time.sleep(1)
driver.find_element_by_id('products_save').click()
time.sleep(1)
driver.find_element_by_id('ott_monthly_budget').send_keys('200000')
driver.find_element_by_id('ott_cpm_sold').send_keys('1.2')
driver.find_element_by_id('ott_btn_calculate_impressions').click()
driver.find_element_by_css_selector("input[type='radio'][name='ott_allocate'][value='impression']").click()
time.sleep(1)
driver.find_element_by_name('ott_no_of_impressions').send_keys('209992')
time.sleep(1)
driver.find_element_by_css_selector("input[type='radio'][name='ott_date'][value='no']").click()
time.sleep(1)
driver.find_element_by_name('ott_start_date').click()
driver.find_element_by_class_name('next').click()
driver.find_element_by_class_name('next').click()
driver.find_element_by_class_name('next').click()
driver.find_element_by_xpath('/html[1]/body[1]/div[5]/div[1]/table[1]/tbody[1]/tr[5]/td[3]').click()
time.sleep(1)
driver.find_element_by_id('allocation_save').click()

time.sleep(1)
driver.find_element_by_class_name('ott').click()
time.sleep(1)
driver.find_element_by_css_selector("input[type='radio'][name='video_ott_tactics'][value='yes']").click()
time.sleep(1)
driver.find_element_by_class_name('video-ott').click()
driver.find_element_by_name('video-ott_add_creative_name_of_ad-1').send_keys('anything to test')
driver.find_element_by_name('video-ott_add_creative_name_of_cta-1').send_keys('something')
driver.find_element_by_name('video-ott_add_creative_name_of_client_url-1').send_keys('type the url here ')
driver.find_element_by_name('video-ott_add_creative_name_of_target_url-1').send_keys('type the target url here ')
driver.find_element_by_name('video-ott_add_creative_name_of_ad_desc-1').send_keys('the quick brown fox jumps over the lazy dog')
time.sleep(1)
driver.find_element_by_name("userfile_video-ott-1[]").send_keys('/home/thamarai/Pictures/0.jpeg')
time.sleep(1)
#driver.find_element_by_xpath('/html[1]/body[1]/div[1]/div[2]/form[1]/div[3]/div[21]/div[1]/div[19]/div[1]/div[1]/button[2]/span[1]').click()
time.sleep(1)
driver.find_element_by_id('video_ott_save').click()
time.sleep(1)
driver.find_element_by_xpath('/html[1]/body[1]/div[1]/div[2]/form[1]/div[3]/div[6]/div[1]/div[2]/div[2]/div[2]/div[1]/span[3]').click()
time.sleep(1)

#youtube
driver.find_element_by_xpath('/html[1]/body[1]/div[1]/div[2]/form[1]/div[3]/div[6]/div[1]/div[2]/div[2]/div[3]/div[1]').click()
driver.find_element_by_id('products_save').click()
time.sleep(1)
driver.find_element_by_css_selector("input[type='number'][name='youtube_budget']").send_keys('200000')
time.sleep(1)
driver.find_element_by_xpath("/html[1]/body[1]/div[1]/div[2]/form[1]/div[3]/div[7]/div[1]/div[5]/div[1]/div[2]/div[1]/div[2]/div[1]/li[1]/label[1]/input[1]").click()
time.sleep(1)
driver.find_element_by_name('youtube_start_date').click()
driver.find_element_by_class_name('next').click()
driver.find_element_by_class_name('next').click()
driver.find_element_by_class_name('next').click()
driver.find_element_by_xpath('/html[1]/body[1]/div[5]/div[1]/table[1]/tbody[1]/tr[5]/td[3]').click()
driver.find_element_by_id('allocation_save').click()
time.sleep(1)
#driver.find_element_by_class_name('btn-attention').click()
driver.find_element_by_xpath('/html[1]/body[1]/div[1]/div[2]/form[1]/div[3]/div[24]/div[1]/div[1]/div[3]/button[1]').click()
time.sleep(1)
driver.find_element_by_name('video_utube_name').send_keys('Name of your Video')
driver.find_element_by_name('video_utube_url').send_keys('Type the Url')
#driver.find_element_by_xpath('/html[1]/body[1]/div[1]/div[2]/form[1]/div[3]/div[25]/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/div[1]/a[1]/div[1]/b[1]').('Top 10%')
#driver.find_element_by_css_selector("ul[type='text'][class='chosen-results highlighted'][data-option-array-index='1']").click()

driver.find_element_by_xpath('/html[1]/body[1]/div[1]/div[2]/form[1]/div[3]/div[25]/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/div[1]/a[1]/div[1]/b[1]').click()
driver.find_element_by_name('video_utube_target_location').send_keys('Type or paste your location')
driver.find_element_by_name("userfile_video-utube-location[]").send_keys('/home/thamarai/Pictures/0.jpeg')
driver.find_element_by_name('video_utube_target_audience').send_keys('Describe Target Audience')
driver.find_element_by_name("userfile_video-utube-audience[]").send_keys('/home/thamarai/Pictures/0.jpeg')
driver.find_element_by_name('video_utube_target_keyword').send_keys('Type keywords here ')
driver.find_element_by_name("userfile_video-utube-keyword[]").send_keys('/home/thamarai/Pictures/0.jpeg')
driver.find_element_by_name('video_utube_topics').send_keys('type the topic name here ')
driver.find_element_by_name('video_utube_video_url').send_keys('type or paste the url here')
driver.find_element_by_id('video_utube_save').click()
time.sleep(1)
driver.find_element_by_xpath('/html[1]/body[1]/div[1]/div[2]/form[1]/div[3]/div[6]/div[1]/div[2]/div[2]/div[3]/div[1]').click()
driver.find_element_by_id('products_save').click()
print(' Report :- All the test pass for Video form \n')
driver.close()