import time 
from selenium import webdriver
driver = webdriver.Chrome('/home/thamarai/Downloads/chromedriver')
driver.get('http://pilot.projecthubapp.com')
driver.maximize_window()
time.sleep(1)
driver.find_element_by_id('username').clear()
driver.find_element_by_id('username').send_keys('mannese@gmail.com')
time.sleep(1)
driver.find_element_by_id('password').clear()
driver.find_element_by_id('password').send_keys('arizona123')
driver.find_element_by_id('recaptcha-submit').click()
driver.find_element_by_id('project request').click()
time.sleep(1)
driver.find_element_by_class_name('btn').click()
time.sleep(1)
driver.find_element_by_class_name('radio').click()
time.sleep(1)
driver.find_element_by_id('existing_client_radio').click()
driver.find_element_by_id('order_name').send_keys('Testing')
time.sleep(1)
driver.find_element_by_id('add_new_product').click()
time.sleep(1)
driver.find_element_by_id('icon-sales').click()
time.sleep(1)
#driver.find_element_by_id('save_goals').click()
#time.sleep(1)
driver.find_element_by_id('goals_save').click()
driver.execute_script("window.scrollTo(0, 500)")
time.sleep(1)
driver.find_element_by_id('product_website').click()
time.sleep(1)
#driver.find_element_by_id('save_products').click()
time.sleep(1)
driver.find_element_by_id('products_save').click()
time.sleep(1)
driver.execute_script("window.scrollTo(0, 500)")
time.sleep(1)
driver.find_element_by_css_selector("button[type='button'][class='product_website btn-attention needs_attention']").click()
time.sleep(1)
driver.find_element_by_name('web_company_name').send_keys('Tyop comany name here')
driver.find_element_by_name('domain_url').send_keys('type company url here')
driver.find_element_by_name('tag_line').send_keys('type tag line ')
driver.find_element_by_name('target_market').send_keys('type target market')
driver.find_element_by_name('service_products_brands').send_keys('type brand info here')
driver.find_element_by_name('brand_point').send_keys('type brand point of difference')
time.sleep(1)
driver.find_element_by_name('address_line2').send_keys('type the address')
driver.find_element_by_name('street_address').send_keys('type full address street name and all')
driver.find_element_by_name('client_city').send_keys('Type your city name')
#driver.find_element_by_class_name('chosen-single').click()
driver.find_element_by_name('phone_number').send_keys('874857583748347 type your phone no')
driver.find_element_by_name('email_for_website').send_keys('xyz.@gmail.com')
driver.find_element_by_name('navigation_pages').send_keys('type info with comma seprated')
driver.find_element_by_name('hosting_url').send_keys('type hosting url here www.anything.com')
driver.find_element_by_name('hosting_username').send_keys('hosting user name ')
driver.find_element_by_name('hosting_password').send_keys('password')
time.sleep(1)
driver.find_element_by_name('wordpress_url').send_keys('type wrodpress url here ')
driver.find_element_by_name('wordpress_username').send_keys('wordpress username')
driver.find_element_by_name('wordpress_password').send_keys('password')
time.sleep(1)
driver.find_element_by_name('cms_ftp_url').send_keys('type url here ')
driver.find_element_by_name('cms_ftp_username').send_keys('type username')
driver.find_element_by_name('cms_ftp_password').send_keys('password')
time.sleep(1)
driver.find_element_by_name('website_pages').send_keys('type,website,pages,with,comma,seprated')
driver.find_element_by_name('website_code').send_keys('type wesite code here')
driver.find_element_by_name('userfile_website[]').send_keys('/home/thamarai/Pictures/github .png')
driver.find_element_by_name('client_likes1').send_keys('url to website clint like one')
driver.find_element_by_name('client_likes2').send_keys('url to website clint like two')
driver.find_element_by_name('client_likes3').send_keys('url to website clint like three')
time.sleep(1)
driver.find_element_by_name('like_reason1').send_keys('reasion one to like website')
driver.find_element_by_name('like_reason2').send_keys('reason two to like website')
driver.find_element_by_name('like_reason3').send_keys('reason three to like the website')
driver.find_element_by_name('other_notes').send_keys('type here the notes ')
driver.find_element_by_id('web_save').click()
print('Report : - All the test pass for WEB form \n')

driver.close()

